spring:
  cloud:
    gateway:
      routes:
        - id: route_auth
          uri: lb://ace-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            - JwtAuthCheckFilter

        - id: route_member
          uri: lb://ace-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            - JwtAuthCheckFilter

        - id: route_question
          uri: lb://ace-question
          predicates:
            - Path=/api/question/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
            - JwtAuthCheckFilter
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求前缀

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: ace-member
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    include: jwt

server:
  port: 8050
